title: Raghuraman's Portfolio
description: A portfolio and blog of Raghuraman's projects, pursuits, and interests.
baseurl: "" # Keep this empty unless your site is in a subpath
url: "https://RogueTex.github.io"
theme: minima
permalink: pretty

# Add links to your About and Blog sections in the header
header_pages:
  - index.html
  - blog.md # Link to the blog page instead of _posts
  - resume.html

# Social media links
social_links:
  github: https://github.com/nctzen0
  linkedin: https://www.linkedin.com/in/raghuraman1
  instagram: https://www.instagram.com/rxghu

