title: Raghuraman | Portfolio
description: FDE and Solutions Engineering portfolio for Raghuraman.
baseurl: "" # Keep this empty unless your site is in a subpath
url: "https://RogueTex.github.io"
theme: minima
permalink: pretty

# Add links to your About and Blog sections in the header
header_pages:
  - index.html
  - blog.md # Link to the blog page instead of _posts
  - resume.html

# Social media links
social_links:
  github: https://github.com/RogueTex
  linkedin: https://www.linkedin.com/in/raghuraman1
